# Mendapatkan Semua Image Path

In [1]:
from glob import glob

In [7]:
fname = glob('data/*/*.png')
fname[-5:]

['data\\9\\95.png',
 'data\\9\\96.png',
 'data\\9\\97.png',
 'data\\9\\98.png',
 'data\\9\\99.png']

# X = path => image => Flatten

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [45]:
x = []
for f in fname:
    x.append(plt.imread(f).flatten())
x = np.array(x)

In [46]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [17]:
X = np.array([plt.imread(f).flatten() for f in fname])
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [18]:
X.shape

(2000, 784)

# y = Path => split => [1]

In [43]:
y = np.array([int(f.split('\\')[1]) for f in fname])
y

array([0, 0, 0, ..., 9, 9, 9])

In [44]:
y.shape

(2000,)

# join jd satu dataframe

In [49]:
df = pd.DataFrame(X, columns=range(1,785))
df

1    2    3    4    5    6    7    8    9    10   ...  775  776  777  \
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

      778  779  780  781  782  783  784  
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
1995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[2000 rows x 784 columns]

In [50]:
df['label'] = y

df.to_csv('data/metadataExercise.csv', index=False)

In [51]:
df.head()

1    2    3    4    5    6    7    8    9   10  ...  776  777  778  779  \
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0   

   780  781  782  783  784  label  
0  0.0  0.0  0.0  0.0  0.0      0  
1  0.0  0.0  0.0  0.0  0.0      0  
2  0.0  0.0  0.0  0.0  0.0      0  
3  0.0  0.0  0.0  0.0  0.0      0  
4  0.0  0.0  0.0  0.0  0.0      0  

[5 rows x 785 columns]